# Generated by Django 4.2.7 on 2023-12-03 10:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 3, 10, 25, 57, 737854)
                    ),
                ),
                ("sale_price", models.FloatField(default=2500000)),
                ("price_difference", models.FloatField(default=10000)),
                ("total_gold_stock", models.FloatField(default=0.0)),
                ("stock_status", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="joined_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 3, 10, 25, 57, 734182)
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "admin"), ("customer", "customer")],
                default="customer",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money_stock", models.FloatField(default=0.0)),
                ("gold_stock", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmsMSG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(default="")),
                (
                    "sendDate",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 3, 10, 25, 57, 734877)
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.userinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleGold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 3, 10, 25, 57, 742213)
                    ),
                ),
                ("money_amount", models.FloatField(default=0.0)),
                ("gold_amount", models.FloatField(default=0.0)),
                ("gold_price", models.ManyToManyField(to="Core.goldprice")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 3, 10, 25, 57, 739909)
                    ),
                ),
                ("money_amount", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyGetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2023, 12, 3, 10, 25, 57, 746130)
                    ),
                ),
                ("money_amount", models.FloatField(default=0.0)),
                ("request_status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldGetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2023, 12, 3, 10, 25, 57, 746565)
                    ),
                ),
                ("gold_amount", models.FloatField(default=0.0)),
                ("request_status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyGold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 3, 10, 25, 57, 743228)
                    ),
                ),
                ("money_amount", models.FloatField(default=0.0)),
                ("gold_amount", models.FloatField(default=0.0)),
                (
                    "buying_type",
                    models.CharField(
                        choices=[
                            ("Add to Wallet", "Add to Wallet"),
                            ("get directly", "get directly"),
                        ],
                        default="Add to Wallet",
                        max_length=15,
                    ),
                ),
                ("gold_price", models.ManyToManyField(to="Core.goldprice")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
