# Generated by Django 4.2.7 on 2023-12-05 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Core", "0003_alter_buygold_buy_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="auth_temp_code",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="auth_temp_code_create_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="smsmsg",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
