# Generated by Django 4.2.7 on 2023-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_userinformation_auth_temp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactions",
            name="status",
            field=models.CharField(
                choices=[
                    (" در انتظار واریز وجه", " در انتظار واریز وجه"),
                    ("واریز موفقیت آمیز", "واریز موفقیت آمیز"),
                    ("واریز با حطا", "واریز با حطا"),
                ],
                default=" در انتظار واریز وجه",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="joined_date",
            field=models.DateTimeField(null=True),
        ),
    ]
