# Generated by Django 4.2.7 on 2023-12-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0005_paymenttransactions_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buygold",
            name="buying_type",
        ),
    ]
