# Generated by Django 4.2.7 on 2023-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0006_remove_buygold_buying_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="buygold",
            name="request_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salegold",
            name="request_status",
            field=models.BooleanField(default=False),
        ),
    ]
