# Generated by Django 4.2.7 on 2023-12-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0007_buygold_request_status_salegold_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactions",
            name="payment_id",
            field=models.CharField(default="11111", max_length=20, null=True),
        ),
    ]
