# Generated by Django 4.2.7 on 2023-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0008_paymenttransactions_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldgetrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("تایید درخواست", "تایید درخواست"),
                    ("در انتظار بررسی", "در انتظار بررسی"),
                    ("رد درخواست", "رد درخواست"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moneygetrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("تایید درخواست", "تایید درخواست"),
                    ("در انتظار بررسی", "در انتظار بررسی"),
                    ("رد درخواست", "رد درخواست"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salegold",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("تایید درخواست", "تایید درخواست"),
                    ("در انتظار بررسی", "در انتظار بررسی"),
                    ("رد درخواست", "رد درخواست"),
                ],
                default="در انتظار بررسی",
                max_length=20,
            ),
        ),
    ]
