# Generated by Django 4.2.7 on 2023-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0009_alter_goldgetrequest_request_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldgetrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("accept", "accept"),
                    ("waiting", "waiting"),
                    ("reject", "reject"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moneygetrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("accept", "accept"),
                    ("waiting", "waiting"),
                    ("reject", "reject"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salegold",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("accept", "accept"),
                    ("waiting", "waiting"),
                    ("reject", "reject"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
